-- Bike Store Business Analytics Report
-- This script contains SQL queries used to analyze key business metrics:
-- • Customer segmentation
-- • Product category performance
-- • Revenue and sales analysis
-- • Average orders per customer
-- • Top revenue-generating customers
-- • Inventory distribution across stores and states
-- • Sales distribution by location
-- • Top 5 products generating the highest revenu
-- • Bottom 5 products (worst-performing) based on revenue generated
--
-- The goal of this analysis is to demonstrate SQL skills in:
-- data aggregation, joins, window functions, CTEs, formatting,
-- and business-oriented insights for decision making.
-- Number of Customers by State
select
	state,
	count(customer_id) as total_customers
from sales.customers
group by state
order by total_customers desc
-- Total Products by Category
select
	c.category_name as [Category Name],
	count(p.category_id) as [Number of Products]
	from production.products as p
	left join production.categories as c
	on p.category_id=c.category_id
group by c.category_name

--Average price per Category
select
	c.category_name as [Category Name],
	concat(cast(avg(p.list_price)as int),' ','$') as [Average Price]
	from production.products as p
	left join production.categories as c
	on p.category_id=c.category_id
group by c.category_name


-- Average Number of Orders per Customer
select
	avg(Nb_of_Or_Per_Cus) as Avg_Customer_Orders
from(select
	customer_id,
	count(order_id) as Nb_of_Or_Per_Cus
	from sales.orders
group by customer_id)t;

-- Total revenue generated for each category
with cat_rev as(select
	c.category_name,
	sum(oi.quantity*oi.list_price* (1-oi.discount)) as revenue
from sales.order_items as oi
left join production.products as p
	on oi.product_id=p.product_id
left join production.categories as c
	on p.category_id=c.category_id
group by c.category_name)
select
	ca.category_name,
	format(ca.revenue, 'N2')+' $' as revenue_formatted
from cat_rev as ca ;

-- Top 10 customers generated by revenue
with cust_rev as (
  select
    o.customer_id,
    sum(oi.quantity * oi.list_price * (1 - oi.discount)) as revenue
  from sales.order_items oi
  join sales.orders o on oi.order_id = o.order_id
  group by o.customer_id
)
select top 10
  cr.customer_id,
  concat(c.first_name,' ', c.last_name) as customer_name,
  format(cr.revenue, 'N2') + ' $' as revenue_formatted
from cust_rev cr
 left join sales.customers as c
 on cr.customer_id=c.customer_id
order by revenue desc

-- Total inventory across states
select
	s.state,
	sum(p.quantity) as total_inventory
from production.stocks as p
	left join sales.stores as s
on p.store_id=s.store_id
group by s.state

-- Distribution of sold items across countries
select
	coalesce(s.state,'Unknown') as state,
	sum(oi.quantity) as sold_items
from sales.order_items as oi
	left join sales.orders as o
on oi.order_id=o.order_id
	left join sales.stores as s
on o.store_id=s.store_id
group by coalesce(s.state,'Unknown')
order by sold_items desc

-- Top 5 products that generate highest revenue
select top 5
p.product_name,
sum(s.quantity*s.list_price*(1-s.discount)) as total_revenue
from sales.order_items as s
left join production.products as p
on s.product_id=p.product_id
group by p.product_name
order by total_revenue desc

-- 5 worst performing products in terms of sales
select top 5
p.product_name,
sum(s.quantity*s.list_price*(1-s.discount)) as total_revenue
from sales.order_items as s
left join production.products as p
on s.product_id=p.product_id
group by p.product_name
order by total_revenue asc
